INHERIT: ../mkdocs.yml

site_dir: ../dist/en
site_url: https://monbug.ca/en/

theme:
  name: material
  language: en

extra:
  alternate:
    - name: Français
      link: /fr/
      lang: fr

    - name: English
      link: /en/
      lang: en
