site_name: MonBUG
site_dir: dist

plugins:
  - include-markdown
  - awesome-nav
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/mon-bug.bsky.social
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@monbug5683
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/monbug/

extra_css:
  - assets/styles/timeline.css
  - assets/styles/general.css
  - assets/styles/image-gallery.css

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.blocks.html

  - pymdownx.snippets:
      check_paths: True
      base_path: .
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

theme:
  name: material
  custom_dir: '../overrides/'
  logo: assets/images/logo.light.svg
  favicon: assets/images/logo.svg

  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
